# Generated by Django 5.0 on 2023-12-13 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='guffadis',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
